#define BTREECHILDLOWERLIMIT 2
#define BTREECHILDUPPERLIMIT 3
#define BTREEKEYLOWERLIMIT (BTREECHILDLOWERLIMIT - 1)
#define BTREEKEYUPPERLIMIT (BTREECHILDUPPERLIMIT - 1)


typedef struct BTreeNode {
  Generic keys[BTREEKEYUPPERLIMIT];
  (struct BTreeNode *) children[BTREECHILDUPPERLIMIT];
} BTNode;
